language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.6"
branches:
  except:
    - piptools-ignore-patch
install:
  - "pip install cram --use-mirrors"
  - "pip install . --use-mirrors"
script:
  - "cram tests/*.t"
