language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.6"
branches:
  except:
    - piptools-ignore-patch
install:
  - "pip install cram"
  - "pip install ."
script:
  - "cram --shell=/bin/bash tests/*.t"
